### ISSUE TITLE
gedit isn't called "Text Editor"

### ISSUE THREAD

**Issue by csmart** [kororaproject/19-beta#5]
We should push this upstream but it's just an annoying cosmetic I worked around years ago, most apps in gnome are called by their description, except the text editor which is called "gedit"

We used to ship our own gedit.desktop file which fixed this but in 19 beta it's still "gedit" not sure why.

**Comment by firnsy** [comment]
it's still gedit because we ship /usr/local/share/applications/gedit.desktop to attempt to override /usr/share/applications/gedit.desktop.

also our mechanism for overriding is Name[en_AU]="Text Editor" which doesn't feel right given the canonical name is Name=gedit, Name[en_CA]=gedit and Name[en_GB]=gedit.

what are we trying to achieve? is it that we want an agnostic name to represent a text editor, what about LOO's writer?

if i type "text" in the search box it "what i would expect" displays both gedit and writer, i may be missing the real problem.

**Comment by csmart** [comment]
yeah, most of the GNOME apps seem to be by name, not description. Just gedit all lowercase looks out of place, but that _is_ the name.

We're removed the desktop files, so closing.
